Bugfix for the issue 'Claims cannot be removed from role'
maqduni/AspNetCore.Identity.RavenDb pull request #14
Opened 2017-07-14 17:42 UTC by michaelschnyder

closes #13

2017-07-15 03:32 UTC, maqduni requested changes
Please make changes to the unit test. Besides that all looks great! Thanks a lot for your contribution!

2017-07-15 03:32 UTC, maqduni commented on test/Maqduni.AspNetCore.Identity.RavenDb.Tests/TestStores.cs
> +        public void RoleWithClaimsRemoveClaimAsync(string roleName, string claimType, string claimValue)
Please rename the function to RoleClaimsRemoveClaimAsync. A agree that you are implying adding and removing claims, but I think it'd be better to have a unified naming pattern for all functions. I like the idea of adding and removing claims, and I can implement it in all of the tests.

2017-07-15 03:32 UTC, maqduni commented on test/Maqduni.AspNetCore.Identity.RavenDb.Tests/TestStores.cs
> +            for (int i = 0; i < 10; i++)
Please just add a single claim, there is no point in adding 10 of them...

2017-07-15 05:10 UTC, maqduni commented on test/Maqduni.AspNetCore.Identity.RavenDb.Tests/TestStores.cs
> +            for (int i = 0; i < 10; i++)
Though it's a good way to point out that claims can be duplicated and by deleting one, all of the dupes will also be gone.

Disregard my first comment, don't make any changes here.

2017-07-16 16:34 UTC, maqduni approved these changes

2017-07-16 16:34 UTC, merged

2017-07-17 08:11 UTC, michaelschnyder commented
just got back to work and already merged :) nice. no need for additional work then?

2017-07-17 14:37 UTC, maqduni commented
No additional work is required. I figured you worked on it at work and decided to just merge and make the adjustments myself, there were very minor. I published package version 1.3.34, please download and test it. Let me know if you have any questions.